### ISSUE TITLE
Encoding is broken

### ISSUE THREAD

**Issue by QtRoS** [ftylitak/qzxing#10]
Result of 
`QImage QZXing::encodeData(const QString& data)`
is incorrect QR Code. Even zxing site can't recognize it.

**Comment by ftylitak** [comment]
Hello QtRoS,

the "encodeData" is a work in progress and it has not yet been included to any official release. Its main part is implemented though there is an issue with the ReedSolomon encoding that i have not yet resolved.

(Here)[https://github.com/ftylitak/qzxing/projects/1#card-263095] you can see a plan for the next release.

**Comment by QtRoS** [comment]
Thank you for the answer!
What's wrong with that part? Can I help you?

**Comment by ftylitak** [comment]
The code part that i am referring to is in file [src/zxing/zxing/common/reedsolomon/ReedSolomonEncoder.cpp](https://github.com/ftylitak/qzxing/blob/master/src/zxing/zxing/common/reedsolomon/ReedSolomonEncoder.cpp#L36)

I have ended up to this part of code since all the rest functionality used in [src/zxing/zxing/qrcode/encoder/QREncoder.cpp](https://github.com/ftylitak/qzxing/blob/master/src/zxing/zxing/qrcode/encoder/QREncoder.cpp) has already been successfully covered through the tests in [src/QZXingTests](https://github.com/ftylitak/qzxing/tree/master/tests/src/QZXingTests). 

All the above code is direct port from the java code of (zxing v2.3)[https://github.com/zxing/zxing/releases/tag/zxing-2.3.0] source code. Thus if you are interested in investigating, you can use that code as a reference as well. 

Your help and your input are very welcomed!

**Comment by fenixrus** [comment]
Will the solution of this issue?
