### ISSUE TITLE
Not able to decode UPC_A

### ISSUE THREAD

**Issue by eliezedeck** [ftylitak/qzxing#107]
Hi,

Using the QZXingLive app (compiled on macOS), I am not able to decode any UPC_A formatted barcodes. I have changed the decoder `QZXing.DecoderFormat_EAN_13 | QZXing.DecoderFormat_UPC_A`.

Only `QZXing.DecoderFormat_EAN_13` works. I'm not sure what is going on, but hope someone could help.

Thanks.

**Comment by eliezedeck** [comment]
To help in debugging, I have used the following image in https://zxing.org/w/decode.jspx and it decoded properly.

![Daily Vits barcode](https://user-images.githubusercontent.com/7553916/57762706-aa2c8980-7708-11e9-99b8-40e8476b5d79.jpg)

**Comment by ftylitak** [comment]
Hello @eliezedeck 

yesterday we had a very valuable contribution in the pull request #106 . May this pull request solves your issue. 

It is not yet integrated to the mainstream of QZXing due to lack of time, though if you feel like having time you could give it a try and give us your feedback. 

In any case,, as soon as this pull request is tested you will be informed.

**Comment by eliezedeck** [comment]
Hi @ftylitak, very valuable indeed. I thought QZXing just inherited all the features of the original `zxing` library and I was under the impression that it should just work. Is there a documentation that lists the currently supported barcode types? (I sure have missed if it does exist).

Anyway, it's getting late here, and so I'll have to check this tomorrow. Thanks for the update.

**Comment by eliezedeck** [comment]
Hey @ftylitak, I went on vacation last week and didn't have time to test. I see the PR hasn't been merged yet... what's the status on this now? More importantly, the reason why the PR isn't merged, I see some issue from `Eism` and I wonder if that is a blocking issue. Thanks

**Comment by ftylitak** [comment]
Hello @eliezedeck 

the main reason why the PR is not merged is because I am very busy these past weeks and i did not have time to proceed. 

Thus, if you feel like having time, use the code from https://github.com/Eism/qzxing/tree/UPCEAN_Extensions to check if this works for you. Then as soon as it is merged into the master branch, you can switch to the main QZXing code.

**Comment by ftylitak** [comment]
The feature is now merged in the master branch of QZXing so you can give it a try.

**Comment by ftylitak** [comment]
I have used the image that you provided above along with the example application QZXingDragNDropTest and the image was decoded successfully. 

![Screenshot from 2019-06-19 15-06-26](https://user-images.githubusercontent.com/550020/59764156-ddcc7780-92a3-11e9-81df-2a6d7e24ed45.png)

Can you do some tests with your own barcodes so as to close the issue?

**Comment by eliezedeck** [comment]
Hi @ftylitak, I'm very busy with a completely different project for the time being. I will test again once the project is completed. For now, we can close this issue since you have tested and it's good. We can always re-open if there are problems.
