### ISSUE TITLE
QZXingFilter orientation

### ISSUE THREAD

**Issue by Eism** [ftylitak/qzxing#120]
Hello @ftylitak !

Yesterday I received an error from clients that the scanner recognizes a barcode for a long time.
After research, I found that the filter gets a rotated image than on videoOutput with autoOrientstion. Because of this, we try to recognize the barcode several times before the image is rotated, this is the cause of the freezes.
This is probably due to the fact that we are taking the frame directly from the camera, and not from videoOutput with autoOrientation.

I made a decision, it is not possible to correct, but it is working.
https://github.com/Eism/qzxing/commit/bafc42c8880294fef1af79a98e4ad2f8b9046555

What do you think about it?

Android, Qt 5.12.3, QZXingLive

**Comment by ftylitak** [comment]
Hello @Eism 

indeed it is a good idea. I have one suggestion to avoid image copying in normal conditions. Since the orientation to my understanding is an integer that denotes the rotation expressed in degrees you could avoid copying the image in case the rotation is zero. So instead of:

https://github.com/Eism/qzxing/blob/5bc0429fd27beb67a439d706a7c4d5809ca3297a/src/QZXingFilter.cpp#L352-L361

it could become:

```cpp
    if(!orientation)
        decode(image_ptr);
    else {
        QImage translatedImage = (*image_ptr).transformed([](QPoint center, int orientation) {
                QMatrix matrix;
                matrix.translate(center.x(), center.y());
                matrix.rotate(-orientation);
                return matrix;
            }((*image_ptr).rect().center(), orientation));

         decode(translatedImage);
    }
```

I will do some measurements to compare your implementation against the approach that QZXing already have when the [tryHarder](https://github.com/ftylitak/qzxing/blob/024d1e26b7ecdd65174baf5308a2c7aea660cb40/src/QZXing.h#L59) is enabled . This is also related to a try to optimize the "tryHarder" operation from issue #104.
