### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by FurkanB190803** [ftylitak/qzxing#131]
How can I use QZXing, can you help?

**Comment by ftylitak** [comment]
Hello @FurkanB190803 

you need to be more specific on your requests. 

Have you read the [README file](https://github.com/ftylitak/qzxing)? 
After reading the above, proceed to compile and run one of the examples in the [examples folder](https://github.com/ftylitak/qzxing/tree/master/examples). 
For instance: 
* [QZXingLive](https://github.com/ftylitak/qzxing/tree/master/examples/QZXingLive)
* [BarcodeEncoder](https://github.com/ftylitak/qzxing/tree/master/examples/BarcodeEncoder)

Do these and if you have any specific problem create a corresponding issue. I am closing this issue as it is not an issue.

**Comment by FurkanB190803** [comment]
Hello Nikolaos Ftylitakis

Your QZxing library is not a problem. Is camera quality important when
decoding QrCode and how can we access the decoded qrcode data with qml
codes?

Can you tell me this?
The readme file will be more useful to be understood than written too
mixed.

Please review your Readme file again. Thank you for writing such a library
was very useful.

28 Ağu 2019 Çar 11:49 tarihinde Nikolaos Ftylitakis <
notifications@github.com> şunu yazdı:

**Comment by ftylitak** [comment]
Hello @FurkanB190803 

i was about to send you an example from the README file though i have seen your code [here](https://github.com/FurkanB190803/QrCode/tree/master/Sal_QrCode) so it is better to talk on your code. 

I have run your code on Linux and it does decode the data properly. I mean that I saw messages in the log being printed by the following line:
https://github.com/FurkanB190803/QrCode/blob/a3b65c16929b712eaff890dc695165104767fc50/Sal_QrCode/Reader.qml#L36

So you did implemented it correctly. 

The reason that you might not succeeded in your tests it is because for this line:
https://github.com/FurkanB190803/QrCode/blob/a3b65c16929b712eaff890dc695165104767fc50/Sal_QrCode/Reader.qml#L43

In this line, we define that we want to capture and process only the center of the image. So the code **Qt.rect(0.25, 0.25, 0.5, 0.5)** means to start from the 25% of the width , and the 25% of the height and keep the remaining 50% of the image. This was done provide less data to the QZXing thus making the decoding quicker.  

You can try this. Change the [line 43](https://github.com/FurkanB190803/QrCode/blob/a3b65c16929b712eaff890dc695165104767fc50/Sal_QrCode/Reader.qml#L43) with this: 

```qml
return videoOutput.mapRectToSource(videoOutput.mapNormalizedRectToItem(Qt.rect(0, 0, 1, 1)));
```

Is it better now? 

PS: if you want we can also talk in your issue: https://github.com/FurkanB190803/QrCode/issues/1

Best regards

**Comment by FurkanB190803** [comment]
Hello Nikolaos Ftylitakis

Thanks for your help.

It was very useful.
------------------------------


30 Eyl 2019 Pzt 19:13 tarihinde Nikolaos Ftylitakis <
notifications@github.com> şunu yazdı:

**Comment by ftylitak** [comment]
Hello Furkan,

I am happy to hear it wokrs for you. In case you come across any other issue just let me know. 

Your comment regarding the update of the README file is noted ;)
