### ISSUE TITLE
Can't decode some vague images.

### ISSUE THREAD

**Issue by zslzxm** [ftylitak/qzxing#158]
![微信图片_20200226104150](https://user-images.githubusercontent.com/30920759/75306647-a1b2d300-5884-11ea-89e0-132308a044ad.jpg)

I can't decode the above image by using QZXing.
But I can decode it with Tencent WeXin easily.
If I enlarge the image, I can decode it with QZXing sometimes, but most time still can't decode it.
Could you please help me to check this issue?
Thank you very much!

**Comment by ftylitak** [comment]
Hello @zslzxm 

This project is based on ZXing project, so the first thing I do in such cases is to check whether the parent project with its latest code is able to decode the image. After submitting the image that you have provided to the online decoder of ZXIng: https://zxing.org/w/decode it turns out that it is also unable to decode it. 

This leaves me with little choices as I do not have better knowledge than the ZXing team on this. 

Maybe if you could find such a "vague" image that could be decoded by https://zxing.org/w/decode and not this project, I could work on it.
