### ISSUE TITLE
Encoding of large text

### ISSUE THREAD

**Issue by MrunaliCTandel** [ftylitak/qzxing#196]
Hi,

I am trying to encode a large string value using QZXing but seems that the resultant QR codes generated are invalid. I am not able to decode the resultant QR codes using QZXing.
While I had a look on the previous similar issues #83 which is marked as closed, somehow the fix didn't work for me.
The string I am trying to encode is "1/1:V1:GD$123456:CO$17/BK/1140:DM$111/100/5/1.0:CT$20/0.0000:CP$77/0.1050*218/0.2844*1459/2.0088:CT$99/2.1974:CP$1600/2.1974*6400/8.8158:CT$100/9.3596:CP$6808/9.3596*9600/13.2018*22400/30.7456:"

Attached are the resultant QR codes.
[Qr[1].pdf](https://github.com/ftylitak/qzxing/files/6405827/Qr.1.pdf)

Thanks,

**Comment by ftylitak** [comment]
Hello @MrunaliCTandel 

I tried to reproduce it using the two examples that QZXing provides, the [BarcodeEncoder](https://github.com/ftylitak/qzxing/tree/master/examples/BarcodeEncoder) and the [https://github.com/ftylitak/qzxing/tree/master/examples/QZXingDragNDropTest](QZXingDragNDropTest). 

In the BarcodeEncoder, I have copy/pasted the input that you provide above, I saved the result Qr code through a screenshot to the separate file and dragged/dropped the file to the QZXingDragNDropTest. The result it that the generated Qr code was successfully recognized. 

![Screenshot from 2021-05-05 15-18-23](https://user-images.githubusercontent.com/550020/117139692-32ecd600-adb5-11eb-87cc-634431275be7.png)

![Screenshot from 2021-05-05 15-19-18](https://user-images.githubusercontent.com/550020/117139759-48fa9680-adb5-11eb-9258-dd02ae06b739.png)

So, since I was not able to reproduce it, I would go towards 2 directions:
a) Make sure you have the latest code
b) we need to check the way you provide the string to the QZXing encoder. Can you share any code part where you do the calls? Do you use it through C++ only? Or do you display it with QML?

**Comment by MrunaliCTandel** [comment]
Hi @ftylitak,

Thanks! You are correct.
I see that in my project code a particular commit of your project was forced in the configuration to generate the static library which belonged to QZXing 2.3.
I updated the library and could generate the QR Codes.
But I see a warning on my Qml where I imported QZXing. Here the only change I made is the version number. Is there any other things I have to additionally do over what I followed for QZXing 2.3?

Thanks once again! :) I know I am almost there.


![image](https://user-images.githubusercontent.com/47138408/117576462-bedb6680-b103-11eb-8e6c-a31383d3cf9f.png)
