### ISSUE TITLE
How can i rotate the captureRect of QZXingFilter

### ISSUE THREAD

**Issue by MichaelSavchenko67** [ftylitak/qzxing#204]
https://github.com/ftylitak/qzxing/blob/9973b3dd786298c6389476058639a25020e5507b/examples/QZXingLive/main.qml#L92

**Comment by ftylitak** [comment]
Hello @MichaelSavchenko67 

I am not really sure what you want to do. I would say it is just a matter how you define the Qt.rect(). The constructor of the Qt.rect takes 4 arguments (x, y, width and height ) just adjust it based on your needs. 

By default, the source code uses decimal values which are the persentage of width or height. 

Was this any helpfull?

**Comment by DenPonomarchuk** [comment]
How do I rotate the readout image? Now the barcode is read vertically, but how to read it horizontally?

**Comment by ftylitak** [comment]
Hello @MichaelSavchenko67  and @DenPonomarchuk 

a long time ago @Eism proposed a solution to this in issue #120 
I have just push a new branch with this solution:  https://github.com/ftylitak/qzxing/tree/qzxingfilter-orientation-support

Since I have an issue with my build environment right now, any of you pull the latest changes from that branch and test it if it working? Otherwise I believe sometime till tomorrow I will manage to test it myself.

**Comment by DenPonomarchuk** [comment]
It works. The only thing is, it is better to use QTransform instead of QMatrix (recommendation from Qt). 
`QTransform matrix;`.

**Comment by Eism** [comment]
I'm happy that after two years my solution became useful :)

**Comment by ftylitak** [comment]
Its was my bad all this time, I had forgotten to merge it back then. 

I have just pushed the latest changes to that branch. I would really appreciate if you could once again verify that it works as needed. As soon as this happens, it will be merged to the master branch. 

Thank you all very much for your contribution and testing!

**Comment by DenPonomarchuk** [comment]
Horizontal reading is successful! The value of the parameter `orientation` being set - works! Thanks for the merge to master.
