### ISSUE TITLE
Examples are outdated! They use Qt Declarative instead Qt Qml & Quick!!!

### ISSUE THREAD

**Issue by JacekMarcinJ** [ftylitak/qzxing#28]
Please fix it as soon as possible...

**Comment by ftylitak** [comment]
Could you be kind enough and take a look at https://github.com/ftylitak/qzxing/tree/master/examples/QZXingLive. Do you consider this as outdated?

The only example that contains Qt Declarative is https://github.com/ftylitak/qzxing/tree/master/examples/QMLBarcodeScanner. Why is that such a problem to you? 

Moreover, an issue when opened needs to be informative. When you point out an issue, refer also the code that proves your sayings. This way, the issue reporting can be helpful and lower the resolution times. Last but not least, the language must be kind and respectful. No one here is obligated to do anything thus your writing can not be dictating. 

Best regards.

**Comment by JacekMarcinJ** [comment]
Hi ftliak!
Thank you for your rapid answer. Sorry if you find my report issue offensive. I was just surprised that some one still use Qt Declarative... In true I try QZXingLive with commented line:
//decoder.setDecoder(QZXing::DecoderFormat_Aztec | QZXing::DecoderFormat_QR_CODE);
And I printed two codes (EAN-8 (with coded '1234567' value) and Data Matrix (with encoded my email)). But sadly it didn't recognize them... But I have wrote simple app and I successfully decode image file with one of the codes. But our expectations is that decode codes from video stream... So: maybe you can give me some advices how to force QZXing to decode codes from stream buffer?!? Or maybe can you give me test codes values which are success fully decode by QZXing library?!?

**Comment by ftylitak** [comment]
Hello @JacekMarcinJ 

sorry for the delay. The QZXingLive example is the code that you are looking for.  It makes use of the [QZXingFilter](https://github.com/ftylitak/qzxing/blob/6d945cce4f0a79a1e84dffc70dc32cbc6e878cda/examples/QZXingLive/main.qml#L85) in order to decode messages as they are provided by video feed. The decoder included in the QZXingFilter item can be fine-tuned. For instance, you can set the enabled decoders. Right now the enabled decoders are: [EAN_13, CODE_39, QR_CODE](https://github.com/ftylitak/qzxing/blob/6d945cce4f0a79a1e84dffc70dc32cbc6e878cda/examples/QZXingLive/main.qml#L98). So this answers your question why you could not decode the DataMatrix and possible the EAN-8. 
 
Right now the project has a low success rate for DataMatrixes though it is a good thing to try out for your self and see.

Feel free to look the example once more and if you are still experiencing problems, sent here and i will try to assist you.

**Comment by ftylitak** [comment]
@JacekMarcinJ 

did you have any progress on this?

**Comment by JacekMarcinJ** [comment]
Yes. I can recognized many codes from video on the fly, but there is other problem. I merge QZXingLive example and multimedia/declarative-camera from Qt examples. Because I want video recording, image capture and codes recognition in one (test) app. And then there is huge problem with camera lock by VideoOutput in QZXing part. I normally need the camera output for video preview in main window. So I manually switch two VideoOutput's sources. For example:
      State {
            name: "BarcodeCapture"
            StateChangeScript {
                script: {
                    camera.stop();
                    viewfinder.visible = false; // z jakiegoś powodu to musi być, bo inaczej się wiesza
                    viewfinder.source = null;
                    camera.captureMode = Camera.CaptureStillImage;
                    camera.focus.focusMode = CameraFocus.FocusContinuous;
                    camera.focus.focusPointMode = CameraFocus.FocusPointAuto;
                    barcodeCapture.source = camera;
                    camera.start();
                    barcodeCapture.recoginitionEnabled = true;
                    //barcodeCapture.visible = true;
                }
            }
        }

But I don't think that this is the "right" or Qt way... Maybe you can give me some advice how to properly handle two VideoOutput objects in the same time with one camera? Switching they visibility does not enough - it does not work for some unknown reason (camera lock happen).
