### ISSUE TITLE
Better encoding API from QML

### ISSUE THREAD

**Issue by oKcerG** [ftylitak/qzxing#31]
Currently when we want to encode a QRCode from QML we call `qzxing.encode(data)` and access it with an image provider at `source: "image://QZXing/latestEncoded"`.

This can be made more declarative by modifying the image provider to be  able to do `source: image://QZXing/data`, others parameter than the data could also be passed if needed in the future (format, error correction, ...).

This has 2 more advantages, when changing the encoded data you don't have to reset the source (emptying it and resetting to the same url) to update the image, and you can display 2 different encoded codes at the same time easily.

If you feel this is a good idea, I could contribute a PR (I already have a PoC working).

**Comment by ftylitak** [comment]
Hello @oKcerG,

indeed your proposal is quite interesting. It would be great if your could contribute this whenever you are ready. 

The solution that exists till now was the most basic implementation that i could do in order to start testing the encoding. By efforts are put on the completion of the encoding backend this is why i have never re-evaluated API of the feature.

Looking forward to your ideas!

**Comment by ftylitak** [comment]
(_A small reminder to avoid any misunderstandings to anyone that might read this issue_)
the QR encoding is not yet finished. It is still buggy. References on its progress can be found here: #10
