### ISSUE TITLE
Build QZXing cavetas

### ISSUE THREAD

**Issue by JacekMarcinJ** [ftylitak/qzxing#35]
Hi
There are two major cavetas when we want to build QZXing:
1) there is no mention around about necessity of adding that line:
`CONFIG += qzxing_qml qzxing_multimedia`
To QZXing.pro in the case we want use it as dll (contrary to just include pri file). Without this line QZXing is pretty useless.
2) there is no mention around about necessity of adding that line:
`DEFINES += QZXING_QML QZXING_MULTIMEDIA`
To the application pro file. Without it we will be confused with "unresolved externals" errors when try to compile.
This should be added to the README.md file.

Other confusing thing is "official" release (currently from past year) - I don't found it very useful: no examples it also lack some files... So I decide to use master branch from github.

thanks and best regards
Jacek

**Comment by ekke** [comment]
next week I want to start to integrate QZXing into some of my projects.
development machine: OSX
target: Android, iOS (later this year Windows 10 mobile)
first step I wanted to do is to build the example from amster branch
thx Jacek providing your experiences - will help me :)

would be great to have a 'HowTo build example app from Master'

**Comment by ftylitak** [comment]
Dear @JacekMarcinJ 

indeed the last release was created on January 2016. Many things have changed since then so it is quite normal that "it lack some files". Also back then, there were examples for QML but nothing specific for smartphones nor QZXingFilter. So yes, it comes to no surprise that if someone wants the latest features, the master branch must be used. These features will be included in the next release which will be created upon the completion of the needed features. 

Now regarding the two points that you make, both of them can be answered by just reading the  README.md that is included in the root folder of the repository. 
1. The CONFIG values are already explained [here](https://github.com/ftylitak/qzxing/tree/master#control-dependencies). Read it first as you should and inform me in case you have any questions.
1. The number 2. are internal macros of the library. These are not to be manually controlled by the users of the library this is why there is no explanation about them. If you experience issues with "unresolved externals" that relate to these macros, it means that you have not read neither the documentation nor the implementation of the examples.

I close this issue as I find no useful information for others.

PS. @ekke : each example should be already implemented in such a way that will not require instructions. Just open the .pro file, compile it and that's it. Of course if you experience any issue, report it back here with a new issue.

Best regards
