### ISSUE TITLE
Sequential decoding from Camera

### ISSUE THREAD

**Issue by swex** [ftylitak/qzxing#5]
As far as I understand now its only possible to decode image by image.
That forces user to interact with application in some way (by clicking decode/capture) I think library must provide way to scan images sequentially and emit signals on Tag found.
Or its possible already and I missed something..?
Again qtquick2 example would be perfect!

**Comment by ftylitak** [comment]
Today i made available a valuable contribution made a month ago, a project that provides an implementation to the continuous image decoding. Moreover, it is QtQuick2 so i would relate it to also issue #4. 

Project QZXingLive at: https://github.com/ftylitak/qzxing/tree/master/examples/QZXingLive

The issues will not yet be closed since i believe that the example project can be further enhanced to either be easier to use or to embed parts of it to the core of the library. 

Either way, your input and comments are important and i look forward to hear from you again.

Best regards

**Comment by swex** [comment]
Thank you, anyway I got to QAbstractVideoFilter myself and problem I've faced now is YUV QVideoFrame format. One more way is to use QVideoProbe but it suffer from the same QVideoFrame to QImage format convertion problem as VideoFilter. So grabToImage on VideoOut probably stiil the best crossplatform way to get QImage from camera.

**Comment by QtRoS** [comment]
@ftylitak I've tried to run QZXingLive on Android. I intended to test QR Code recognition. It doesn't capture anything at all. All decodings are unsuccessful. What can be wrong with it?

**Comment by ftylitak** [comment]
@swex  Today a [pull request](https://github.com/ftylitak/qzxing/commit/37ca7a13e1ffa424301d38a6e64e909490e40135) was merged into the code that adds support of the YUV to the QZXingLive project. Could you check if this fills your requirements?

@QtRoS the comming days i will do some tests on Android and i will let you know.

**Comment by Matzurai** [comment]
Changing the Camera element in main.qml:35 to
`Camera
    {
        id:camera
        focus{
            focusMode: Camera.FocusContinuous
            focusPointMode: Camera.FocusPointCenter
        }
    }
`
helps A LOT.
