### ISSUE TITLE
Memory increase in Debug

### ISSUE THREAD

**Issue by m-obi** [ftylitak/qzxing#61]
Hello,

the memory increase in Debug, but not in Release, when I'm using decodeImage(). In Release its alternating but not going up like in Debug.

**Comment by ftylitak** [comment]
Could you provide some info? Which platform are you targeting? Which compiler?

**Comment by Ohicram** [comment]
I have to report the same issue. In particular compiling from Qt Creator with Microsoft Visual Studio C++ Compiler 15.0 in Debug got 2833 Issues reporting: :`-1: warning: Debugger encountered an exception: Exception at 0x7ff80f49a388, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance)` and then Invalid address specified to `RtlValidateHeap( 000001FB067C0000, 000001FB0AB66D90 ) `from Application Output window.
This is happening only in debug mode. Googling it seems due to a memory corruption:

>  "you will see the error concerning heap corruption in debug builds because heap checking is being carried out when freeing memory only in the debug C++ runtime libraries.
> 
> Usual causes are writing past the end of an array you've allocated on the heap, using delete / delete [] wrongly etc."

**Comment by ftylitak** [comment]
PR #205 might fix this issue. 
It will be closed and in case of new evidence that the crash still exists, feel free to reopen.
