### ISSUE TITLE
Wont recognize QZXing.h

### ISSUE THREAD

**Issue by dtavares07** [ftylitak/qzxing#64]
Hi.

I've successfully compile the library on a raspberry pi and add it to my project, but when I try to include it QT won't recognize it.

Any idea here.

Best Regards,
Daniel Tavares

**Comment by ftylitak** [comment]
Hello Daniel,

i would require more information in order to help you. 
What do you mean by saying "try to include it QT"? 
Could you provide the compilation logs?

**Comment by dtavares07** [comment]
I compiled the library as static. Then I've created a project in QT and I added the library to the .pro file using the QT tool to add libraries. When I wrote on main.cpp #include <QZXing.h> QT didn't recognize the include.

**Comment by ftylitak** [comment]
This sound to me that you have used wrong "Include path" when importing the library. 

By compiling QZXing project to generate the static library, you have created one .a file that you have specified its path to the dialog during the addition of the library to your project (field "Library FIle"): 

![2](https://user-images.githubusercontent.com/550020/35501183-d99cb112-04e1-11e8-860c-1eb9de7a8528.png)

Automatically, the dialogue uses the same path also for field "Include Path". This is not correct because the actual .h files of QZXing are located in their source folder. 

Thus, you have two options:
a) Use the correct path in the "Include Path"
b) Compile QZXing without using "Shadow build" in the project settings to generate the .a file in the same folder as the .h files. 

Do you confirm the above?

**Comment by ftylitak** [comment]
@dtavares07 

do you have any update?

**Comment by ftylitak** [comment]
I will consider this as closed. In case your issue still exist, just reopen the issue.
