### ISSUE TITLE
not read qrcode data  from file with jpg format.

### ISSUE THREAD

**Issue by hulaishun** [ftylitak/qzxing#71]
the jpg file is: ![game1](https://user-images.githubusercontent.com/15058616/36018067-4b6fba2e-0db5-11e8-8019-e7c327580053.jpg)

the qrcode data is:http://qstx.rxdouniu.cn/admin/scan_return?erweimaId=210099

but use the example of QZXingDragNDropTest, it not read qrcode data from the file.

thank you very much!

**Comment by hulaishun** [comment]
my development machine is: win10，x64, ide is vs2015/qtcreator, qt version is 5.9.4.

**Comment by ftylitak** [comment]
Hello @hulaishun 

the example image that you have sent has a speciality. It does not comply to the Qr Code standards because it does not have "Quiet Zone" around it. 

![800px-qr_code_structure_example_3 svg](https://user-images.githubusercontent.com/550020/36019031-924feeac-0d86-11e8-906e-fe79fd0d07e4.png)
[Source](https://en.wikipedia.org/wiki/File:QR_Code_Structure_Example_3.svg)

So if the image was like the following, it would be recognized:
![36018067-4b6fba2e-0db5-11e8-8019-e7c327580053](https://user-images.githubusercontent.com/550020/36019067-bf2f7c3a-0d86-11e8-802e-b0b8cc02d045.jpg)

This special case it not planted to be supported. In case you are interested in changing the code to support it you are more than welcomed.

**Comment by hulaishun** [comment]
@ftylitak 
you are great.
thank you for your enthusiastic recommend.
i am understood.
thank you very much!!!
