### ISSUE TITLE
module "QZXing" is not installed in qml @ pelagicore/meta-pelux

### ISSUE THREAD

**Issue by TM9412** [ftylitak/qzxing#73]
Hi,

I clone this library and it is working fine in QML on my qt creator. Now i am try to add this in my project but in that it is not always showing 
**QZXing.h no such file or directory !!**

i already generate QR code in x86 QT 
reference : module "QZXing" is not installed in qml at QT plateform

**Comment by ftylitak** [comment]
Have you followed these steps: 
1. add **include(QZXing/QZXing.pri)** in your pro file
1. do not add **CONFIG += staticlib**. I am mentioning this because in #72 you had included it though it was not needed in that case.
1. copy the QZXing folder in the same folder that the .pro file of your project is.
1. add the following two lines to the main.cpp  
```cpp
QZXing::registerQMLTypes();
QZXing::registerQMLImageProvider(engine);
```

The **QZXing.h no such file or directory !!** is related to the steps 1 and 3, and the **reference : module "QZXing" is not installed in qml at QT platform** with step 4.

If you are still experiencing issues, I will need better explanation and/or logs.

**Comment by TM9412** [comment]
i added this library in my project on x86 system  and i am run project on other platform so during that an getting this error

QML Image: Invalid image provider: image://qzxing/encode/123456

**Comment by ftylitak** [comment]
Try to use correct casing to the QZXing.
```qml
text: image://QZXing/encode/123456
```

**Comment by TM9412** [comment]
I gave correct case in qml file 
        source: "image://QZXing/encode/" + inputField.text;

and i added library name is QZXing

**Comment by ftylitak** [comment]
Have you added in the .pro file the following line before the include statement of the QZXing.pri? 
```
CONFIG += qzxing_qml
```
If you are still experiencing problems, I need more information to be able to help you. 
I am guessing that you could be registering the image provider to an engine different from the one that loads the QML files. Though, I can not go further in guesses if you do not share pieces of code and/or logs along with a detailed problems that you are having. In your first message you mentioned something different from the problem that you mentioned in your second message.

**Comment by TM9412** [comment]
I am workinh on pelagicore/meta-pelux plateform on that it is not working !
i did all the required #72 <https://github.com/ftylitak/qzxing/issues/72>
changes.

**Comment by ftylitak** [comment]
Interesting, automotive eh.

Have you tried to compile and run your initial/test project on that platform? 
Also, to be clear, you are continuing to receive only the following error:

    reference : module "QZXing" is not installed in qml at QT platform

correct?

**Comment by TM9412** [comment]
correct and question title is also correct now !

**Comment by oKcerG** [comment]
@TM9412 Can you share your main.cpp ?

**Comment by TM9412** [comment]
Which main.cpp 
my pelux project 's main.cpp ??

my full sample code is here <[#72](https://github.com/ftylitak/qzxing/issues/72)>

**Comment by TM9412** [comment]
HI @oKcerG  @ftylitak 

Can you please provide Yocto recipe for "QZxing":  ?
similar to this [bb file](https://github.com/nickdademo/meta-nickdademo/blob/master/qzxing/qzxing_1.3.bb)

and that library should be install in /usr/include directory

**Comment by TM9412** [comment]
Hi @oKcerG  @ftylitak 

Can you please tell me How this line code is working ?
source: "image://QZXing/encode/" + inputField.text;

In QML it is working fine and it is able to generate QRcode but in my work project it is showing
warning : QML Image: Invalid image provider: image://qzxing/encode/
and not able to create QRcode.

**Comment by ftylitak** [comment]
Hello @TM9412 

I have seen all your questions on this subject, here, and in Qt forum and in stackoverflow.

If I were you, I would start by reading the documentation of [QQuickImageProvider](http://doc.qt.io/qt-5/qquickimageprovider.html#details). It provides a clear explanation of the implementation that has been done in QZXing. 

Also, you need to be clearer in your messages. For instance, your sentence "In QML it is working fine" is confusing. I understand by your previous messages that you meant to say that it is working fine for for x86-x64 platforms.  

Now, regarding your issue,  as I said before, since I suppose that you want to integrate this to an already existing project, I believe that either you do not call 

```cpp
QZXing::registerQMLImageProvider(engine);
```

or the engine instance that you provide to _registerQMLImageProvider_ function is not the same engine as the one used in the application to load the views.

In case you continue to face issues, the only way is to share code parts. In case you do not want to publicly share code, you can sent me a private message.

**Comment by TM9412** [comment]
yes @ftylitak   
 the engine instance that you provide to registerQMLImageProvider function is not the same engine as the one used in the application to load the views.

due to this problem I am not able to generate QR-code 
I passed the same engine and  able to generate qrcode

Thank you for Help .!!
