### ISSUE TITLE
QZxing cannot find barcode on DIN A4 scan

### ISSUE THREAD

**Issue by Nonononoki** [ftylitak/qzxing#96]
I used both the command line **and** the Drag 'n Drop GUI example but I couldn't get either working. Shortening the length of the image with GIMP works well, but I'd love to get it working in its original size. Other propritary Barcode scanner apps also work well. Maybe I have to configure something in the code?

It's a simple Code 39 barcode on a blank DIN A4 scan.

![05](https://user-images.githubusercontent.com/11612388/48758392-313ffe00-eca0-11e8-89db-c0cef72f577b.png)

**Comment by ftylitak** [comment]
Hello @Nonononoki 

this has to do with a known issue where we can not decode images that are bigger than 999x999. For this reason the library automatically downscales any image greater that the above resolution to 999x999. 

Thus, in your case, since the image has resolution: 1654x2340, it will be downscaled to 999x706. Because the barcode is very small compared to the rest of the file, the barcode will get even smaller and probably unreadable. 

I have not yet found why the library can not decode images bigger than 999x999 so I will keep this issue open and try to find a proper solution.

**Comment by ftylitak** [comment]
Hello @Nonononoki ,

today i have pushed a new branch with a small fix that could solve your issue. 

Could you checkout the branch "no-image-resizing" and let me know your results?

SHA: 928c642483d07fd0f73f28295edcf90f6bae8571

**Comment by Nonononoki** [comment]
Hey @ftylitak,

works great now. I hope there will be a new release with this fix soon ;)
